service: aws-lambda-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - 

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  
  addTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /addTask
          method: post
  
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /getTasks
          method: get
  
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /getTask/{id}
          method: get

  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /updateTask/{id}
          method: put

resources: 
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

